# Ka-MLOps DVC Pipeline Configuration (Fixed)
stages:
  data_generation:
    cmd: python scripts/ka_scripts/generate_training_data.py 1
    deps:
    - scripts/ka_scripts/generate_training_data.py
    outs:
    - data/raw/ka_lending_club_dataset.csv
    
  data_preprocessing:
    cmd: python src/ka_modules/ka_data_preprocessing.py
    deps:
    - data/raw/ka_lending_club_dataset.csv
    - src/ka_modules/ka_data_preprocessing.py
    outs:
    - data/processed/ka_files/ka_X_train.csv
    - data/processed/ka_files/ka_X_test.csv
    - data/processed/ka_files/ka_y_train.csv
    - data/processed/ka_files/ka_y_test.csv
    
  model_training:
    cmd: python src/ka_modules/ka_model_training.py
    deps:
    - data/processed/ka_files/ka_X_train.csv
    - data/processed/ka_files/ka_X_test.csv
    - data/processed/ka_files/ka_y_train.csv
    - data/processed/ka_files/ka_y_test.csv
    - src/ka_modules/ka_model_training.py
    outs:
    - models/ka_models/ka_loan_default_model.joblib
    metrics:
    - metrics/ka_metrics/ka_model_metrics.json