# Model Parameters Configuration
# This file contains all configurable parameters for the ML pipeline

# Data Processing
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  test_size: 0.2
  validation_size: 0.2
  random_state: 42
  target_column: "class"
  
  # Feature engineering
  categorical_features:
    - "Attribute1"
    - "Attribute3" 
    - "Attribute4"
    - "Attribute6"
    - "Attribute7"
    - "Attribute9"
    - "Attribute10"
    - "Attribute12"
    - "Attribute14"
    - "Attribute15"
    - "Attribute17"
    - "Attribute19"
    - "Attribute20"
  
  numerical_features:
    - "Attribute2"
    - "Attribute5"
    - "Attribute8"
    - "Attribute11"
    - "Attribute13"
    - "Attribute16"
    - "Attribute18"

# Model Training
model:
  algorithm: "RandomForestClassifier"
  parameters:
    n_estimators: 200
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42
    n_jobs: -1
    class_weight: "balanced"
  
  # Cross-validation
  cv_folds: 5
  scoring_metric: "roc_auc"
  
  # Model selection
  hyperparameter_tuning:
    enabled: true
    method: "grid_search"  # or "random_search", "bayesian"
    param_grid:
      n_estimators: [100, 200, 300]
      max_depth: [5, 10, 15, null]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]

# MLflow Configuration
mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "loan_default_prediction"
  model_name: "loan_default_classifier"
  artifact_path: "model"
  
  # S3 artifact store (for production)
  s3_bucket: "loan-default-mlflow-artifacts"
  aws_region: "us-east-1"

# Model Evaluation
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "roc_auc"
    - "average_precision"
  
  threshold: 0.5
  
  # Performance thresholds for retraining
  retraining_thresholds:
    min_auc: 0.75
    min_accuracy: 0.70
    max_drift_score: 0.1

# Data Validation
data_validation:
  # Data quality checks
  missing_value_threshold: 0.1  # 10% missing values max
  duplicate_threshold: 0.05     # 5% duplicates max
  
  # Data drift detection
  drift_detection:
    reference_window_days: 30
    detection_window_days: 7
    statistical_tests:
      - "kolmogorov_smirnov"
      - "chi_squared"
      - "population_stability_index"
    significance_level: 0.05

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 30
  log_level: "info"
  
  # Rate limiting
  rate_limit:
    requests_per_minute: 100
    requests_per_hour: 1000
  
  # Model serving
  model_cache_ttl: 3600  # 1 hour in seconds
  batch_prediction_max_size: 1000

# Monitoring
monitoring:
  # Prometheus metrics
  metrics_port: 8001
  metrics_path: "/metrics"
  
  # Performance monitoring
  latency_buckets: [0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1.0, 2.5, 5.0, 7.5, 10.0]
  
  # Alerting thresholds
  alerts:
    error_rate_threshold: 0.05      # 5% error rate
    latency_p95_threshold: 1.0      # 1 second P95 latency
    prediction_volume_drop: 0.5     # 50% drop in predictions
    model_accuracy_drop: 0.1        # 10% accuracy drop

# Database Configuration
database:
  # PostgreSQL for metrics and monitoring
  postgres:
    host: "localhost"
    port: 5432
    database: "loan_default_monitoring"
    username: "postgres"
    password: "password"
    
  # Connection pooling
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30

# AWS Configuration
aws:
  region: "us-east-1"
  
  # S3 buckets
  s3:
    data_bucket: "loan-default-data"
    model_bucket: "loan-default-models" 
    artifacts_bucket: "loan-default-artifacts"
  
  # ECR repository
  ecr:
    repository_name: "loan-default-mlops"
    
  # RDS
  rds:
    instance_class: "db.t3.micro"
    allocated_storage: 20
    
# Kubernetes Configuration  
kubernetes:
  namespace: "loan-default"
  
  # Deployment configuration
  deployment:
    replicas: 3
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  
  # Service configuration
  service:
    type: "LoadBalancer"
    port: 80
    target_port: 8000

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  
  # Log destinations
  handlers:
    - "console"
    - "file"
    - "cloudwatch"  # for AWS
  
  # Log file configuration
  file:
    path: "logs/loan_default.log"
    max_size: "100MB"
    backup_count: 5

# CI/CD Configuration
cicd:
  # Testing
  test_coverage_threshold: 80
  
  # Deployment
  deployment_strategy: "rolling"
  health_check_timeout: 300
  
  # Environments
  environments:
    - "development"
    - "staging" 
    - "production"