data_preprocessing:
  random_state: 42
  scale_features: true
  test_size: 0.2
model_evaluation:
  classification_threshold: 0.5
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  - auc
model_training:
  max_depth: 10
  min_samples_leaf: 2
  min_samples_split: 5
  n_estimators: 100
  random_state: 42
