data_preprocessing:
  test_size: 0.2
  random_state: 42
  scale_features: true

model_training:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 42

model_evaluation:
  classification_threshold: 0.5
  metrics: ['accuracy', 'precision', 'recall', 'f1', 'auc']
