apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab-testing-api
  namespace: loan-default
  labels:
    app: ab-testing-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ab-testing-api
  template:
    metadata:
      labels:
        app: ab-testing-api
    spec:
      containers:
      - name: ab-testing-api
        image: ab-testing-api:latest
        ports:
        - containerPort: 8003
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ab-testing-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ab-testing-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: ab-testing-config
              key: DB_NAME
        - name: DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: ab-testing-config
              key: DB_SCHEMA
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: ab-testing-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ab-testing-secrets
              key: DB_PASSWORD
        - name: EXPERIMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: ab-testing-config
              key: EXPERIMENT_NAME
        - name: CONTROL_MODEL
          valueFrom:
            configMapKeyRef:
              name: ab-testing-config
              key: CONTROL_MODEL
        - name: TREATMENT_MODEL
          valueFrom:
            configMapKeyRef:
              name: ab-testing-config
              key: TREATMENT_MODEL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ab-testing-config
              key: LOG_LEVEL
        - name: API_PORT
          value: "8003"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi" 
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ab-testing-service
  namespace: loan-default
  labels:
    app: ab-testing-api
spec:
  selector:
    app: ab-testing-api
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
    name: http
  type: ClusterIP
