apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-api
  namespace: loan-default  # Same namespace as your existing app
  labels:
    app: loan-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-api
  template:
    metadata:
      labels:
        app: loan-api
    spec:
      containers:
      - name: loan-api
        image: python:3.9-slim
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          value: "8002"
        command: ["python", "-m", "uvicorn", "api_prometheus:app", "--host", "0.0.0.0", "--port", "8002"]
        volumeMounts:
        - name: app-code
          mountPath: /app
        workingDir: /app
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: app-code
        configMap:
          name: loan-api-code
---
apiVersion: v1
kind: Service
metadata:
  name: loan-api-service
  namespace: loan-default
  labels:
    app: loan-api
spec:
  selector:
    app: loan-api
  ports:
  - name: http
    port: 8002
    targetPort: 8002
  type: ClusterIP