# Update your .github/workflows/ka_mlops_cicd_fixed.yml
# Replace the deploy-production job with this:

  deploy-production:
    needs: [integration-tests, build-and-push]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    
    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name loan-eks-simple
    
    - name: Deploy retrained model to production (REAL DEPLOYMENT)
      run: |
        echo "===================================================="
        echo "🚀 DEPLOYING RETRAINED KA MODEL TO PRODUCTION"
        echo "===================================================="
        
        # Create unique timestamp for this deployment
        DEPLOY_TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        IMAGE_TAG="ka-cicd-${DEPLOY_TIMESTAMP}-${{ github.run_number }}"
        
        # Use the existing ECR image but with proper tagging
        EXISTING_IMAGE="365021531163.dkr.ecr.ap-south-1.amazonaws.com/ka-mlops-api:latest"
        NEW_IMAGE_URI="365021531163.dkr.ecr.ap-south-1.amazonaws.com/ka-mlops-api:$IMAGE_TAG"
        
        echo "📦 Retagging latest image with unique tag: $IMAGE_TAG"
        
        # Pull, retag, and push the latest image with unique tag
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 365021531163.dkr.ecr.ap-south-1.amazonaws.com
        docker pull $EXISTING_IMAGE
        docker tag $EXISTING_IMAGE $NEW_IMAGE_URI
        docker push $NEW_IMAGE_URI
        
        echo "🔄 Updating Kubernetes deployment with NEW image..."
        echo "📦 New image: $NEW_IMAGE_URI"
        
        # REAL KUBERNETES UPDATE (this creates new pods!)
        kubectl set image deployment/ka-mlops-api ka-api=$NEW_IMAGE_URI -n loan-default
        
        echo "⏳ Waiting for rollout to complete..."
        kubectl rollout status deployment/ka-mlops-api -n loan-default --timeout=300s
        
        echo ""
        echo "✅ Verifying NEW pods created..."
        kubectl get pods -n loan-default -l app=ka-mlops-api
        
        echo ""
        echo "📊 Deployment history:"
        kubectl rollout history deployment/ka-mlops-api -n loan-default
        
        echo ""
        echo "🎉 SUCCESS: Retrained model deployed via CI/CD!"
        echo "🔄 Pipeline triggered REAL retraining deployment!"
        echo "===================================================="